name: Test Dispatch

on:
  workflow_dispatch:
  push:
    branches: [feature/azure-cicd-test]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "Hello from manual dispatch!"
